#!/bin/bash

KERNEL_DIR=/workspace/android_kernel_sony_sdm845
CLANG_DIR=/workspace/zy
WORK_DIR=/workspace
export KBUILD_BUILD_USER=ekkusa
export KBUILD_BUILD_HOST=miyo
BotToken=
ID=

anykernel3(){
rm -rf $WORK_DIR/Anykernel
git clone --depth=1 https://github.com/Miiyo/AnyKernel3- -b Toku $WORK_DIR/Anykernel
}

Info(){
DATE=$(TZ=Asia/Singapore date +%d'-'%m'-'%y'_'%I':'%M)
VERSION=$(make kernelversion)
CORES=$(nproc --all)
BRANCH=$(git rev-parse --abbrev-ref HEAD)
COMPILER=$($CLANG_DIR/bin/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')
TAG=$(echo $RANDOM | md5sum | head -c 6; echo;)
}

checktype(){
if [[ $KERNEL_DEFCONFIG = *"kddi"* ]];
then
type=kddi
else
type=global
fi
}

ksucheck(){
if grep -R "CONFIG_HAVE_KPROBES" arch/arm64/configs/
then
KSU_GIT_VERSION=$(cd $KERNEL_DIR/KernelSU; /usr/bin/env PATH=$$PATH:/usr/bin:/usr/local/bin git rev-list --count HEAD)
KSU=$((10000 + KSU_GIT_VERSION + 200))
else
KSU=n/a
fi
}

checkdevice(){
    if [[ $KERNEL_DEFCONFIG = *"akari"* ]];
    then
    DEVICE="Sony Xperia XZ2 (akari)"
    DeviceName1=akari
    DeviceName2=akari_kddi
    DeviceName3=H8296
    else
        if [[ $KERNEL_DEFCONFIG = *"akatsuki"* ]];
        then
        DEVICE="Sony Xperia XZ3 (akatsuki)"
        DeviceName1=akatsuki
        DeviceName2=H9436
        else
            if [[ $KERNEL_DEFCONFIG = *"apollo"* ]];
            then
            DEVICE="Sony Xperia XZ2C (apollo)"
            DeviceName1=apollo
            DeviceName2=H8324
            else
                if [[ $KERNEL_DEFCONFIG = *"aurora"* ]];
                then
                DEVICE="Sony Xperia XZ2P (aurora)"
                DeviceName1=aurora
                DeviceName2=H8166
                fi
            fi
        fi
    fi
}

compile(){
BUILD_START=$(date +"%s")
make O=out ARCH=arm64 ${KERNEL_DEFCONFIG}
PATH="${CLANG_DIR}/bin:${PATH}" \
make -j$(nproc --all) O=out \
                      ARCH=arm64 \
                      CC=clang \
                      LD=ld.lld \
                      AR=llvm-ar \
                      NM=llvm-nm \
                      OBJCOPY=llvm-objcopy \
                      OBJDUMP=llvm-objdump \
                      STRIP=llvm-strip \
                      CROSS_COMPILE=aarch64-linux-gnu- \
                      CROSS_COMPILE_ARM32=arm-linux-gnueabi-
}

# Functions
msg() {
	curl -X POST "https://api.telegram.org/bot$BotToken/sendMessage" -d chat_id="$ID" \
	-d text="$1"
}

file() {
	curl -F document=@"$1" "https://api.telegram.org/bot$BotToken/sendDocument" \
	-F chat_id="$ID"  \
	-F caption="$2"
}

kernelbuild(){
msg "Toku - Kernel Build has been triggered.
Date: $DATE
Device: $DEVICE
Type : $type
KSU : $KSU
Version: $VERSION
Clang: $COMPILER
[$TAG]
"
}

flashable(){
if [ -f out/arch/arm64/boot/Image.gz-dtb ]
then
cp out/arch/arm64/boot/Image.gz-dtb $WORK_DIR/Anykernel
cd $WORK_DIR/Anykernel
sed -i "s/kernel\.for=placeholder/kernel.for=$type/" "anykernel.sh"
sed -i "s/device\.name=placeholder/device.name=$DEVICE/" "anykernel.sh"
sed -i "s/kernelsu\.version=placeholder/kernelsu.version=$KSU/" "anykernel.sh"
sed -i "s/device\.name1=/device.name1=$DeviceName1/" "anykernel.sh"
sed -i "s/device\.name2=/device.name2=$DeviceName2/" "anykernel.sh"
sed -i "s/device\.name3=/device.name3=$DeviceName3/" "anykernel.sh"
zip -r9 MiyoToku-$variant-$DATE.zip * -x .git README.md */placeholder
cp $WORK_DIR/Anykernel/MiyoToku-$variant-$DATE.zip $WORK_DIR/
BUILD_END=$(date +"%s")
DIFF=$((BUILD_END - BUILD_START))
else
echo 'error'
fi
}

upload(){
file "/workspace/MiyoToku-$variant-$DATE.zip" "Kernel Compiled. [$TAG]
Build took : $((DIFF / 60)) minute(s) and $((DIFF % 60)) second(s)"
}

cleanup(){
rm -rf $WORK_DIR/MiyoToku*
}

if [ "$1" == "-msg" ]; then
    msg "$2"
fi

if [ "$1" == "-file" ]; then
    file "$2"
fi

if [ "$1" == "compile" ]; then
    variant=$2
    KERNEL_DEFCONFIG="tama_${variant}_defconfig"
    anykernel3
    cleanup
    cd ${KERNEL_DIR}
    rm -rf out
    Info
    ksucheck
    checktype
    checkdevice
    Info
    kernelbuild
    compile
    flashable
    upload
fi
